id = "lumenhush-theme"
name = "Lumenhush Theme"
version = "0.0.1"
schema_version = 1
authors = ["Pedro Nhamirre"]
description = "A calm dark theme with warm accents and low-contrast color separation for effortless code reading."
repository = "https://github.com/pedronhamirre/lumenhush-theme"
